// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7l4uspADH_pbEIHEW2d700U9WZOfxZ_U',
    appId: '1:827138641520:web:5972dd658b92e4ac89eeb5',
    messagingSenderId: '827138641520',
    projectId: 'raasta-roadmap-web',
    authDomain: 'raasta-roadmap-web.firebaseapp.com',
    storageBucket: 'raasta-roadmap-web.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtOSIjGP_AT1pl8RodUFuaSjDyZygOPm0',
    appId: '1:827138641520:android:7237470860ba703589eeb5',
    messagingSenderId: '827138641520',
    projectId: 'raasta-roadmap-web',
    storageBucket: 'raasta-roadmap-web.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOoYq9LupzRNwj3QF1GASmBe7DCuU1z0Y',
    appId: '1:827138641520:ios:a175a2272474594189eeb5',
    messagingSenderId: '827138641520',
    projectId: 'raasta-roadmap-web',
    storageBucket: 'raasta-roadmap-web.appspot.com',
    iosClientId: '827138641520-f9r462eastfene2febbvetrhp9h6an8u.apps.googleusercontent.com',
    iosBundleId: 'com.ahadhashmi.raasta',
  );
}
